chapters = [
    {"starting_line":491,"book": "Introductory", "book_name": "Introductory", "chapter": "I", "chapter_name": "Introductory"},
    {"starting_line":837,"book": "I", "book_name": "WAGES AND CAPITAL", "chapter": "I", "chapter_name": "The current doctrine of wages—its insufficiency"},
    {"starting_line":1265,"book": "I", "book_name": "WAGES AND CAPITAL", "chapter": "II", "chapter_name": "The meaning of the terms"},
    {"starting_line":1852,"book": "I", "book_name": "WAGES AND CAPITAL", "chapter": "III", "chapter_name": "Wages not drawn from capital, but produced by the labor"},
    {"starting_line":2467,"book": "I", "book_name": "WAGES AND CAPITAL", "chapter": "IV", "chapter_name": "The maintenance of laborers not drawn from capital"},
    {"starting_line":2772,"book": "I", "book_name": "WAGES AND CAPITAL", "chapter": "V", "chapter_name": "The real functions of capital"},
    {"starting_line":3076,"book": "II", "book_name": "POPULATION AND SUBSISTENCE", "chapter": "I", "chapter_name": "The Malthusian theory, its genesis and support"},
    {"starting_line":3458,"book": "II", "book_name": "POPULATION AND SUBSISTENCE", "chapter": "II", "chapter_name": "Inferences from facts"},
    {"starting_line":4283,"book": "II", "book_name": "POPULATION AND SUBSISTENCE", "chapter": "III", "chapter_name": "Inferences from analogy"},
    {"starting_line":4599,"book": "II", "book_name": "POPULATION AND SUBSISTENCE", "chapter": "IV", "chapter_name": "Disproof of the Malthusian theory"},
    {"starting_line":4986,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "I", "chapter_name": "The inquiry narrowed to the laws of distribution—necessary relation of these laws"},
    {"starting_line":5351,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "II", "chapter_name": "Rent and the law of rent"},
    {"starting_line":5610,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "III", "chapter_name": "Interest and the cause of interest"},
    {"starting_line":6104,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "IV", "chapter_name": "Of spurious capital and of profits often mistaken for interest"},
    {"starting_line":6290,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "V", "chapter_name": "The law of interest"},
    {"starting_line":6553,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "VI", "chapter_name": "Wages and the law of wages"},
    {"starting_line":6967,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "VII", "chapter_name": "Correlation and co-ordination of these laws"},
    {"starting_line":7040,"book": "III", "book_name": "THE LAWS OF DISTRIBUTION", "chapter": "VIII", "chapter_name": "The statics of the problem thus explained"},
    {"starting_line":7201,"book": "IV", "book_name": "EFFECT OF MATERIAL PROGRESS UPON THE DISTRIBUTION OF WEALTH", "chapter": "I", "chapter_name": "The dynamics of the problem yet to seek"},
    {"starting_line":7286,"book": "IV", "book_name": "EFFECT OF MATERIAL PROGRESS UPON THE DISTRIBUTION OF WEALTH", "chapter": "II", "chapter_name": "Effect of increase of population upon the distribution of wealth"},
    {"starting_line":7699,"book": "IV", "book_name": "EFFECT OF MATERIAL PROGRESS UPON THE DISTRIBUTION OF WEALTH", "chapter": "III", "chapter_name": "Effect of improvements in the arts upon the distribution of wealth"},
    {"starting_line":8033,"book": "IV", "book_name": "EFFECT OF MATERIAL PROGRESS UPON THE DISTRIBUTION OF WEALTH", "chapter": "IV", "chapter_name": "Effect of the expectation raised by material progress"},
    {"starting_line":8236,"book": "V", "book_name": "THE PROBLEM SOLVED", "chapter": "I", "chapter_name": "The primary cause of recurring paroxysms of industrial depression"},
    {"starting_line":8830,"book": "V", "book_name": "THE PROBLEM SOLVED", "chapter": "II", "chapter_name": "The persistence of poverty amid advancing wealth"},
    {"starting_line":9356,"book": "VI", "book_name": "THE REMEDY", "chapter": "I", "chapter_name": "Insufficiency of remedies currently advocated"},
    {"starting_line":10257,"book": "VI", "book_name": "THE REMEDY", "chapter": "II", "chapter_name": "The true remedy"},
    {"starting_line":10371,"book": "VII", "book_name": "JUSTICE OF THE REMEDY", "chapter": "I", "chapter_name": "Injustice of private property in land"},
    {"starting_line":10827,"book": "VII", "book_name": "JUSTICE OF THE REMEDY", "chapter": "II", "chapter_name": "Enslavement of laborers the ultimate result of private property in land"},
    {"starting_line":11166,"book": "VII", "book_name": "JUSTICE OF THE REMEDY", "chapter": "III", "chapter_name": "Claim of land owners to compensation"},
    {"starting_line":11481,"book": "VII", "book_name": "JUSTICE OF THE REMEDY", "chapter": "IV", "chapter_name": "Property in land historically considered"},
    {"starting_line":12007,"book": "VII", "book_name": "JUSTICE OF THE REMEDY", "chapter": "V", "chapter_name": "Property in land in the United States"},
    {"starting_line":12347,"book": "VIII", "book_name": "APPLICATION OF THE REMEDY", "chapter": "I", "chapter_name": "Private property in land inconsistent with the best use of land"},
    {"starting_line":12516,"book": "VIII", "book_name": "APPLICATION OF THE REMEDY", "chapter": "II", "chapter_name": "How equal rights to the land may be asserted and secured"},
    {"starting_line":12692,"book": "VIII", "book_name": "APPLICATION OF THE REMEDY", "chapter": "III", "chapter_name": "The proposition tried by the canons of taxation"},
    {"starting_line":13121,"book": "VIII", "book_name": "APPLICATION OF THE REMEDY", "chapter": "IV", "chapter_name": "Indorsements and objections"},
    {"starting_line":13401,"book": "IX", "book_name": "EFFECTS OF THE REMEDY", "chapter": "I", "chapter_name": "Of the effect upon the production of wealth"},
    {"starting_line":13592,"book": "IX", "book_name": "EFFECTS OF THE REMEDY", "chapter": "II", "chapter_name": "Of the effect upon distribution and thence upon production"},
    {"starting_line":13805,"book": "IX", "book_name": "EFFECTS OF THE REMEDY", "chapter": "III", "chapter_name": "Of the effect upon individuals and classes"},
    {"starting_line":14010,"book": "IX", "book_name": "EFFECTS OF THE REMEDY", "chapter": "IV", "chapter_name": "Of the changes that would be wrought in social organization and social life"},
    {"starting_line":14595,"book": "X", "book_name": "THE LAW OF HUMAN PROGRESS", "chapter": "I", "chapter_name": "The current theory of human progress—its insufficiency"},
    {"starting_line":15040,"book": "X", "book_name": "THE LAW OF HUMAN PROGRESS", "chapter": "II", "chapter_name": "Differences in civilization—to what due"},
    {"starting_line":15541,"book": "X", "book_name": "THE LAW OF HUMAN PROGRESS", "chapter": "III", "chapter_name": "The law of human progress"},
    {"starting_line":16206,"book": "X", "book_name": "THE LAW OF HUMAN PROGRESS", "chapter": "IV", "chapter_name": "How modern civilization may decline"},
    {"starting_line":16734,"book": "X", "book_name": "THE LAW OF HUMAN PROGRESS", "chapter": "V", "chapter_name": "The central truth"},
    {"starting_line":17013,"book": "CONCLUSION", "book_name": "CONCLUSION", "chapter": "I", "chapter_name": "The problem of individual life"}
]